### ISSUE TITLE
cannot assign a logo image to facebook and google+ posts

### ISSUE THREAD

**Issue by cirocorvino** [pe7er/db8socialmediashare#4]
Hi,
I assigned a logo image via "url logo image for pinterest"  field but while for pinterest's post is ok for the other social network icon links continue to appear the google+ logo image in the post's message.
Could it be possible let to show the logo image selected by the pinterest logo field also for the posts sended to the other social networks?
Thank you
Ciro

**Comment by pe7er** [comment]
Hi Ciro,
Thank you for your suggestion. I added the Pinterest Logo because you need something to send to Pinterest when putting a link on it. 

I don't think that you can add the logo image on the other social media. Twitter, Facebook & Google+ will all add something from your site to it. E.g. for Facebook you'll need to define an Open Graph object on your page: https://developers.facebook.com/docs/web/tutorials/scrumptious/open-graph-object

Kind regards,
Peter

**Comment by cirocorvino** [comment]
Thank you Peter,
your control works great, I found the solution to this issue, the same 
as you described, and solved it adding open graph meta tags.
Thank you for make your control available for free.
If you have some sharable works, I share them on g+ if you like.
Kind regards
Ciro


Il 30/03/2015 23:21, Peter Martin ha scritto:

**Comment by pe7er** [comment]
Hi Ciro,
Good to hear that you've solved it!

Yesterday I released a new version: 1.6.0. The new version has Conditional loading CSS + "Fontawesome" Alternative Layout. 

If you like the module, you're welcome to add a review at:
http://extensions.joomla.org/extensions/extension/social-web/social-share/db8-social-media-share

Thanks,
Peter

**Comment by cirocorvino** [comment]
Hi Peter,
you are on my g+ page: 
https://plus.google.com/u/0/104644778882602727503/posts
thank you I'll see your new upgrade as soon as possible.
Ciro

Il 31/03/2015 11:47, Peter Martin ha scritto:

**Comment by pe7er** [comment]
Thanks!
